name: pb-monorepo

volumes:
  pg_data:
  redis_data:
  kafka_data:

services:
  # ---------------------------------------------------------------------------
  # PostgreSQL
  # ---------------------------------------------------------------------------
  pg:
    image: postgres:18.3-alpine
    container_name: pb_databases
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
      POSTGRES_EXTRA_DATABASES: # TODO => adicionar os nomes dos bancos de cada service
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]

  # ---------------------------------------------------------------------------
  # Redis
  # ---------------------------------------------------------------------------
  redis:
    image: redis:7.4-alpine
    container_name: pb_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  # ---------------------------------------------------------------------------
  # Kong API Gateway
  # ---------------------------------------------------------------------------
  kong:
    image: kong:3.9.1
    container_name: pb_kong
    environment:
      KONG_DATABASE: "off" # Modo DB-less -> (kong sem banco de dados)
      KONG_ADMIN_LISTEN: 0.0.0.0:8001 # Admin API -> escuta todas interfaces na porta 8001
      KONG_ADMIN_GUI_URL: http://localhost:8002 # URL da UI
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml # Caminho do arquivo de config do Kong

      # Logs do Kong API Gateway
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000" # Proxy (API)
      - "8001:8001" # API (Admin)
      - "8002:8002" # UI -> http://localhost:8002
      - "8443:8443" # Proxy SSL (HTTPs)
      - "8444:8444" # API (Admin) (HTTPs)
    volumes:
      - ./docker/kong:/kong:ro
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------------------------------------------------------------------------
  # Kafka (KRaft) + Kafka UI
  # ---------------------------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: pb_kafka
    ports:
      - "9092:9092" # -> localhost
      - "29092:29092" # -> docker
    environment:
      CLUSTER_ID: "pb-kafka-cluster" # -> ID único do cluster
      KAFKA_NODE_ID: "1" # -> ID único do broker
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false" # -> cria tópicos automaticamente ao usá-los (desligar em prod)
      KAFKA_PROCESS_ROLES: "broker,controller" # -> define que este node é broker + controller

      # 1 -> vem do KAFKA_NODE_ID
      # kafka -> nome do serviço no compose
      # 9093 -> vem do listener: CONTROLLER://0.0.0.0:9093 em KAFKA_LISTENERS
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093" # -> lista controllers no quorum
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #  -> nome do listener usado pelo controller

      # PLAINTEXT 9092 → para apps externos (localhost)
      # DOCKER 29092 → para comunicação entre containers Docker
      # CONTROLLER 9093 → para o controller (KRaft)
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,   DOCKER://0.0.0.0:29092,
        CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://localhost:9092, DOCKER://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "DOCKER"

      # Configurações de replicação para tópicos do Kafka definidas como "1" para ambiente de dev
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server=localhost:9092 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  kafka-ui:
    image: kafbat/kafka-ui:v1.5.0
    container_name: pb_kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-ui"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      DYNAMIC_CONFIG_ENABLED: "true"

  # ---------------------------------------------------------------------------
  # Toxiproxy
  # ---------------------------------------------------------------------------
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    container_name: pb_toxiproxy
    ports:
      - "8474:8474"

  # ---------------------------------------------------------------------------
  # Prometheus + Grafana
  # ---------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: pb_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:11.5.10
    container_name: pb_grafana
    ports:
      - "3002:3000"

  # ---------------------------------------------------------------------------
  # Microservices + Eureka Server
  # ---------------------------------------------------------------------------

  eureka:
    container_name: eureka-server
    build:
      context: ./services/eureka-server/docker
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
