spring:
  application:
    name: geolocalization

  datasource:
    url: jdbc:postgresql://pg:5432/geolocalization
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    "[com.edu.infnet.pb]": TRACE
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "

management:
  tracing:
    sampling:
      probability: 1.0 # 100% dos tracings gerados será exportado

  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info

otel:
  exporter:
    otlp:
      endpoint: "http://jaeger:4318"
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
