input {
    http {
      port => 5044
      codec => json
    }
  }

filter {
    mutate {
      rename => { "[log][level]" => "log_level" }
      rename => { "[log][logger]" => "log_logger" }
      rename => { "[process][thread][name]" => "thread_name" }
    }
}

output {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "payments-logs"
    }
    stdout {
      codec => rubydebug
    }
}