input {
  tcp {
    port => 5045
    codec => json_lines
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[service.name]}-%{+YYYY.MM.dd}"  # 1 diferente index por dia
  }
# Mostra os logs no terminal do container — útil para debug
  stdout {
    codec => rubydebug
  }
}

