global:
  scrape_interval: 5s

scrape_configs:
  - job_name: kong-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ["kong:8001"]
        labels:
          gateway: "Kong"

  - job_name: eureka-server-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["eureka-server:8761"]
        labels:
          application: "Discovery Server"
