_format_version: "3.0"

services:
  - name: adm-dashboard-service
    url: http://adm-dashboard:8081
    routes:
      - name: adm-dashboard-routes
        paths: ["/adm-dashboard"]
        protocols:
          - http
        strip_path: true

  - name: community-service
    url: http://community:8083
    routes:
      - name: community-routes
        paths: ["/community"]
        protocols:
          - http
        strip_path: true

  - name: geolocalization-service
    url: http://geolocalization:8084
    routes:
      - name: geolocalization-routes
        paths: ["/geolocalization"]
        protocols:
          - http
        strip_path: true

  - name: payments-service
    url: http://payments:8085
    routes:
      - name: payments-routes
        paths: ["/payments"]
        protocols:
          - http
        strip_path: true

  - name: users-service
    url: http://users:8082
    routes:
      - name: users-routes
        paths: ["/users"]
        protocols:
          - http
        strip_path: true

  - name: stickers-service
    url: http://stickers:8087
    routes:
      - name: stickers-routes
        paths: ["/stickers"]
        protocols:
          - http
        strip_path: true

  - name: store-service
    url: http://store:8088
    routes:
      - name: store-routes
        paths: ["/store"]
        protocols:
          - http
        strip_path: true

plugins:
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  - name: cors
    config:
      origins:
        - "http://localhost:3000" # frontend (dev)
      methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
      headers: [Accept, Content-Type, Authorization]
