spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://pg:5432/store
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          public:
            key: classpath:app.pub

app:
  kafka:
    topics:
      stock-updated: stock-updated
      payment-confirmed: payment-confirmed
      user-events: user-events
      order-created: order-created
      order-cancelled: order-cancelled
      order-status-changed: order-status-changed


server:
  port: 8088

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    "[com.edu.infnet.pb]": TRACE
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info
          - mappings

otel:
  exporter:
    otlp:
      endpoint: "http://jaeger:4318"
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
