INSERT INTO stickers (sticker_code, name, team, type)
VALUES
    ('00', 'Panini Logo - We Are Panini', 'Panini', 'PANINI_SPECIAL'),
    ('FWC 1', 'Official Emblem', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 2', 'Official Emblem', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 3', 'Official Mascots', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 4', 'Official Slogan', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 5', 'Official Ball', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 6', 'Canada - Host Countries & Cities', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 7', 'Mexico - Host Countries & Cities', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 8', 'USA - Host Countries & Cities', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 9', 'Italy 1934 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 10', 'Uruguay 1950 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 11', 'West Germany 1954 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 12', 'Brazil 1962 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 13', 'West Germany 1974 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 14', 'Argentina 1986 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 15', 'Brazil 1994 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 16', 'Brazil 2002 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 17', 'Italy 2006 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 18', 'Germany 2014 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('FWC 19', 'Argentina 2022 - World Cup History', 'World Cup History', 'FIFA_WORLD_CUP_SPECIAL'),
    ('ALG 1', 'Team Logo', 'Algeria', 'TEAM_LOGO'),
    ('ALG 2', 'Alexis Guendouz', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 3', 'Ramy Bensebaini', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 4', 'Youcef Atal', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 5', 'Rayan Aït-Nouri', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 6', 'Mohamed Amine Tougai', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 7', 'Aïssa Mandi', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 8', 'Ismael Bennacer', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 9', 'Houssem Aquar', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 10', 'Hicham Boudaoui', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 11', 'Ramiz Zerrouki', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 12', 'Nabil Bentalab', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 13', 'Team Photo', 'Algeria', 'TEAM_PHOTO'),
    ('ALG 14', 'Farés Chaibi', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 15', 'Riyad Mahrez', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 16', 'Said Benrahma', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 17', 'Anis Hadj Moussa', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 18', 'Amine Gouiri', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 19', 'Baghdad Bounedjah', 'Algeria', 'PLAYER_STICKER'),
    ('ALG 20', 'Mohammed Amoura', 'Algeria', 'PLAYER_STICKER'),
    ('ARG 1', 'Team Logo', 'Argentina', 'TEAM_LOGO'),
    ('ARG 2', 'Emiliano Martinez', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 3', 'Nahuel Molina', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 4', 'Cristian Romero', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 5', 'Nicolas Otamendi', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 6', 'Nicolas Tagliafico', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 7', 'Leonardo Balerdi', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 8', 'Enzo Fernandez', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 9', 'Alexis Mac Allister', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 10', 'Rodrigo De Paul', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 11', 'Exequiel Palacios', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 12', 'Leandro Paredes', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 13', 'Team Photo', 'Argentina', 'TEAM_PHOTO'),
    ('ARG 14', 'Nico Paz', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 15', 'Franco Mastantuono', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 16', 'Nico Gonzalez', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 17', 'Lionel Messi', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 18', 'Lautaro Martinez', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 19', 'Julian Alvarez', 'Argentina', 'PLAYER_STICKER'),
    ('ARG 20', 'Giuliano Simeone', 'Argentina', 'PLAYER_STICKER'),
    ('AUS 1', 'Team Logo', 'Australia', 'TEAM_LOGO'),
    ('AUS 2', 'Mathew Ryan', 'Australia', 'PLAYER_STICKER'),
    ('AUS 3', 'Joe Gauci', 'Australia', 'PLAYER_STICKER'),
    ('AUS 4', 'Harry Souttar', 'Australia', 'PLAYER_STICKER'),
    ('AUS 5', 'Alessandro Circati', 'Australia', 'PLAYER_STICKER'),
    ('AUS 6', 'Jordan Bos', 'Australia', 'PLAYER_STICKER'),
    ('AUS 7', 'Aziz Behich', 'Australia', 'PLAYER_STICKER'),
    ('AUS 8', 'Cameron Burgess', 'Australia', 'PLAYER_STICKER'),
    ('AUS 9', 'Lewis Miller', 'Australia', 'PLAYER_STICKER'),
    ('AUS 10', 'Milos Degenek', 'Australia', 'PLAYER_STICKER'),
    ('AUS 11', 'Jackson Irvine', 'Australia', 'PLAYER_STICKER'),
    ('AUS 12', 'Riley McGree', 'Australia', 'PLAYER_STICKER'),
    ('AUS 13', 'Team Photo', 'Australia', 'TEAM_PHOTO'),
    ('AUS 14', 'Aiden O''Neill', 'Australia', 'PLAYER_STICKER'),
    ('AUS 15', 'Connor Metcalfe', 'Australia', 'PLAYER_STICKER'),
    ('AUS 16', 'Patrick Yazbek', 'Australia', 'PLAYER_STICKER'),
    ('AUS 17', 'Craig Goodwin', 'Australia', 'PLAYER_STICKER'),
    ('AUS 18', 'Kusini Vengi', 'Australia', 'PLAYER_STICKER'),
    ('AUS 19', 'Nestory Irankunda', 'Australia', 'PLAYER_STICKER'),
    ('AUS 20', 'Mohamed Touré', 'Australia', 'PLAYER_STICKER'),
    ('AUT 1', 'Team Logo', 'Austria', 'TEAM_LOGO'),
    ('AUT 2', 'Alexander Schlager', 'Austria', 'PLAYER_STICKER'),
    ('AUT 3', 'Patrick Pentz', 'Austria', 'PLAYER_STICKER'),
    ('AUT 4', 'David Alaba', 'Austria', 'PLAYER_STICKER'),
    ('AUT 5', 'Kevin Danso', 'Austria', 'PLAYER_STICKER'),
    ('AUT 6', 'Philipp Lienhart', 'Austria', 'PLAYER_STICKER'),
    ('AUT 7', 'Stefan Posch', 'Austria', 'PLAYER_STICKER'),
    ('AUT 8', 'Phillipp Mwene', 'Austria', 'PLAYER_STICKER'),
    ('AUT 9', 'Alexander Prass', 'Austria', 'PLAYER_STICKER'),
    ('AUT 10', 'Xaver Schlager', 'Austria', 'PLAYER_STICKER'),
    ('AUT 11', 'Marcel Sabitzer', 'Austria', 'PLAYER_STICKER'),
    ('AUT 12', 'Konrad Laimer', 'Austria', 'PLAYER_STICKER'),
    ('AUT 13', 'Team Photo', 'Austria', 'TEAM_PHOTO'),
    ('AUT 14', 'Florian Grillitsch', 'Austria', 'PLAYER_STICKER'),
    ('AUT 15', 'Nicolas Seiwald', 'Austria', 'PLAYER_STICKER'),
    ('AUT 16', 'Romano Schmid', 'Austria', 'PLAYER_STICKER'),
    ('AUT 17', 'Patrick Wimmer', 'Austria', 'PLAYER_STICKER'),
    ('AUT 18', 'Christoph Baumgartner', 'Austria', 'PLAYER_STICKER'),
    ('AUT 19', 'Michael Gregoritsch', 'Austria', 'PLAYER_STICKER'),
    ('AUT 20', 'Marko Arnautović', 'Austria', 'PLAYER_STICKER'),
    ('BEL 1', 'Team Logo', 'Belgium', 'TEAM_LOGO'),
    ('BEL 2', 'Thibaut Courtois', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 3', 'Arthur Theate', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 4', 'Timothy Castagne', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 5', 'Zeno Debast', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 6', 'Brandon Mechele', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 7', 'Maxim De Cuyper', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 8', 'Thomas Meunier', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 9', 'Youri Tielemans', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 10', 'Amadou Onana', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 11', 'Nicolas Raskin', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 12', 'Alexis Saelemaekers', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 13', 'Team Photo', 'Belgium', 'TEAM_PHOTO'),
    ('BEL 14', 'Hans Vanaken', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 15', 'Kevin De Bruyne', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 16', 'Jérémy Doku', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 17', 'Charles De Ketelaere', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 18', 'Leandro Trossard', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 19', 'Loïs Openda', 'Belgium', 'PLAYER_STICKER'),
    ('BEL 20', 'Romelu Lukaku', 'Belgium', 'PLAYER_STICKER'),
    ('BIH 1', 'Team Logo', 'Bosnia and Herzegovina', 'TEAM_LOGO'),
    ('BIH 2', 'Nikola Vasilj', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 3', 'Amer Dedic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 4', 'Sead Kolasinac', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 5', 'Tarik Muharemovic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 6', 'Nihad Mujakic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 7', 'Nikola Katic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 8', 'Amir Hadziahmetovic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 9', 'Benjamin Tahirovic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 10', 'Armin Gigovic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 11', 'Ivan Sunjic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 12', 'Ivan Basic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 13', 'Team Photo', 'Bosnia and Herzegovina', 'TEAM_PHOTO'),
    ('BIH 14', 'Dzenis Burnic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 15', 'Esmir Bajraktarevic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 16', 'Amar Memic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 17', 'Ermedin Demirovic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 18', 'Edin Dzeko', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 19', 'Samed Bazdar', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BIH 20', 'Haris Tabakovic', 'Bosnia and Herzegovina', 'PLAYER_STICKER'),
    ('BRA 1', 'Team Logo', 'Brazil', 'TEAM_LOGO'),
    ('BRA 2', 'Alisson', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 3', 'Bento', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 4', 'Marquinhos', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 5', 'Éder Militão', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 6', 'Gabriel Magalhães', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 7', 'Danilo', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 8', 'Wesley', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 9', 'Lucas Paquetá', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 10', 'Casemiro', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 11', 'Bruno Guimarães', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 12', 'Luiz Henrique', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 13', 'Team Photo', 'Brazil', 'TEAM_PHOTO'),
    ('BRA 14', 'Vinicius Júnior', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 15', 'Rodrygo', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 16', 'João Pedro', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 17', 'Matheus Cunha', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 18', 'Gabriel Martinelli', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 19', 'Raphinha', 'Brazil', 'PLAYER_STICKER'),
    ('BRA 20', 'Estévão', 'Brazil', 'PLAYER_STICKER'),
    ('CAN 1', 'Team Logo', 'Canada', 'TEAM_LOGO'),
    ('CAN 2', 'Dayne St.Clair', 'Canada', 'PLAYER_STICKER'),
    ('CAN 3', 'Alphonso Davies', 'Canada', 'PLAYER_STICKER'),
    ('CAN 4', 'Alistair Johnston', 'Canada', 'PLAYER_STICKER'),
    ('CAN 5', 'Samuel Adekugbe', 'Canada', 'PLAYER_STICKER'),
    ('CAN 6', 'Riche Larvea', 'Canada', 'PLAYER_STICKER'),
    ('CAN 7', 'Derek Cornelius', 'Canada', 'PLAYER_STICKER'),
    ('CAN 8', 'Moïse Bombito', 'Canada', 'PLAYER_STICKER'),
    ('CAN 9', 'Kamal Miller', 'Canada', 'PLAYER_STICKER'),
    ('CAN 10', 'Stephen Eustáquio', 'Canada', 'PLAYER_STICKER'),
    ('CAN 11', 'Ismaël Koné', 'Canada', 'PLAYER_STICKER'),
    ('CAN 12', 'Jonathan Osorio', 'Canada', 'PLAYER_STICKER'),
    ('CAN 13', 'Team Photo', 'Canada', 'TEAM_PHOTO'),
    ('CAN 14', 'Jacob Shaffelburg', 'Canada', 'PLAYER_STICKER'),
    ('CAN 15', 'Mathieu Choinière', 'Canada', 'PLAYER_STICKER'),
    ('CAN 16', 'Niko Sigur', 'Canada', 'PLAYER_STICKER'),
    ('CAN 17', 'Tajon Buchanan', 'Canada', 'PLAYER_STICKER'),
    ('CAN 18', 'Liam Millar', 'Canada', 'PLAYER_STICKER'),
    ('CAN 19', 'Cyle Larin', 'Canada', 'PLAYER_STICKER'),
    ('CAN 20', 'Jonathan David', 'Canada', 'PLAYER_STICKER'),
    ('CIV 1', 'Team Logo', 'Côte d''Ivoire', 'TEAM_LOGO'),
    ('CIV 2', 'Yahia Fofana', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 3', 'Ghislain Konan', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 4', 'Wilfried Singo', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 5', 'Odilon Kossounou', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 6', 'Evan Ndicka', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 7', 'Willy Boly', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 8', 'Emmanuel Agbadou', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 9', 'Ousmane Diomande', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 10', 'Franck Kessie', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 11', 'Seko Fofana', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 12', 'Ibrahim Sangare', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 13', 'Team Photo', 'Côte d''Ivoire', 'TEAM_PHOTO'),
    ('CIV 14', 'Jean-Philippe Gbamin', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 15', 'Amad Diallo', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 16', 'Sébastien Haller', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 17', 'Simon Adingra', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 18', 'Yan Diomande', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 19', 'Evann Guessand', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('CIV 20', 'Oumar Diakite', 'Côte d''Ivoire', 'PLAYER_STICKER'),
    ('COD 1', 'Team Logo', 'DR Congo', 'TEAM_LOGO'),
    ('COD 2', 'Lionel Mpasi', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 3', 'Aaron Wan-Bissaka', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 4', 'Axel Tuanzebe', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 5', 'Arthur Masuaku', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 6', 'Chancel Mbemba', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 7', 'Joris Kayembe', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 8', 'Charles Pickel', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 9', 'Ngal''ayel Mukau', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 10', 'Edo Kayembe', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 11', 'Samuel Moutoussamy', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 12', 'Noah Sadiki', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 13', 'Team Photo', 'DR Congo', 'TEAM_PHOTO'),
    ('COD 14', 'Théo Bongonda', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 15', 'Meschak Elia', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 16', 'Yoane Wissa', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 17', 'Brian Cipenga', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 18', 'Fiston Mayele', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 19', 'Cédric Bakambu', 'DR Congo', 'PLAYER_STICKER'),
    ('COD 20', 'Nathanaël Mbuku', 'DR Congo', 'PLAYER_STICKER'),
    ('COL 1', 'Team Logo', 'Colombia', 'TEAM_LOGO'),
    ('COL 2', 'Camilo Vargas', 'Colombia', 'PLAYER_STICKER'),
    ('COL 3', 'David Ospina', 'Colombia', 'PLAYER_STICKER'),
    ('COL 4', 'Dávinson Sánchez', 'Colombia', 'PLAYER_STICKER'),
    ('COL 5', 'Yerry Mina', 'Colombia', 'PLAYER_STICKER'),
    ('COL 6', 'Daniel Munoz', 'Colombia', 'PLAYER_STICKER'),
    ('COL 7', 'Johan Mojica', 'Colombia', 'PLAYER_STICKER'),
    ('COL 8', 'Jhon Lucumí', 'Colombia', 'PLAYER_STICKER'),
    ('COL 9', 'Santiago Arias', 'Colombia', 'PLAYER_STICKER'),
    ('COL 10', 'Jefferson Lerma', 'Colombia', 'PLAYER_STICKER'),
    ('COL 11', 'Kevin Castaño', 'Colombia', 'PLAYER_STICKER'),
    ('COL 12', 'Richard Rios', 'Colombia', 'PLAYER_STICKER'),
    ('COL 13', 'Team Photo', 'Colombia', 'TEAM_PHOTO'),
    ('COL 14', 'James Rodriguez', 'Colombia', 'PLAYER_STICKER'),
    ('COL 15', 'Juan Fernando Quintero', 'Colombia', 'PLAYER_STICKER'),
    ('COL 16', 'Jorge Carrascal', 'Colombia', 'PLAYER_STICKER'),
    ('COL 17', 'Jon Arias', 'Colombia', 'PLAYER_STICKER'),
    ('COL 18', 'Jhon Cordova', 'Colombia', 'PLAYER_STICKER'),
    ('COL 19', 'Luis Suarez', 'Colombia', 'PLAYER_STICKER'),
    ('COL 20', 'Luis Diaz', 'Colombia', 'PLAYER_STICKER'),
    ('CPV 1', 'Team Logo', 'Cape Verde', 'TEAM_LOGO'),
    ('CPV 2', 'Vozinha', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 3', 'Logan Costa', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 4', 'Pico', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 5', 'Diney', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 6', 'Steven Moreira', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 7', 'Wagner Pina', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 8', 'Joao Paulo', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 9', 'Yannick Semedo', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 10', 'Kevin Pina', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 11', 'Patrick Andrade', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 12', 'Jamiro Monteiro', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 13', 'Team Photo', 'Cape Verde', 'TEAM_PHOTO'),
    ('CPV 14', 'Deroy Duarte', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 15', 'Garry Rodrigues', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 16', 'Jovane Cabral', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 17', 'Ryan Mendes', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 18', 'Dailon Livramento', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 19', 'Willy Semedo', 'Cape Verde', 'PLAYER_STICKER'),
    ('CPV 20', 'Bebe', 'Cape Verde', 'PLAYER_STICKER'),
    ('CRO 1', 'Team Logo', 'Croatia', 'TEAM_LOGO'),
    ('CRO 2', 'Dominik Livaković', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 3', 'Duje Caleta-Car', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 4', 'Josko Gvardiol', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 5', 'Josip Stanišić', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 6', 'Luka Vušković', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 7', 'Josip Sutalo', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 8', 'Kristijan Jakic', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 9', 'Luka Modrić', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 10', 'Mateo Kovacic', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 11', 'Martin Baturina', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 12', 'Lovro Majer', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 13', 'Team Photo', 'Croatia', 'TEAM_PHOTO'),
    ('CRO 14', 'Mario Pasalic', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 15', 'Petar Sucic', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 16', 'Ivan Perišić', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 17', 'Marco Pasalic', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 18', 'Ante Budimir', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 19', 'Andrej Kramarić', 'Croatia', 'PLAYER_STICKER'),
    ('CRO 20', 'Franjo Ivanovic', 'Croatia', 'PLAYER_STICKER'),
    ('CUW 1', 'Team Logo', 'Curaçao', 'TEAM_LOGO'),
    ('CUW 2', 'Eloy Room', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 3', 'Armando Obispo', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 4', 'Sherel Floranus', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 5', 'Jurien Gaari', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 6', 'Joshua Brenet', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 7', 'Roshon Van Eijma', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 8', 'Shurandy Sambo', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 9', 'Livano Comenencia', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 10', 'Godfried Roemeratoe', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 11', 'Juninho Bacuna', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 12', 'Leandro Bacuna', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 13', 'Team Photo', 'Curaçao', 'TEAM_PHOTO'),
    ('CUW 14', 'Tahith Chong', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 15', 'Kenji Gorre', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 16', 'Jearl Margaritha', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 17', 'Jurgen Locadia', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 18', 'Jeremy Antonisse', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 19', 'Gervane Kastaneer', 'Curaçao', 'PLAYER_STICKER'),
    ('CUW 20', 'Sontje Hansen', 'Curaçao', 'PLAYER_STICKER'),
    ('CZE 1', 'Team Logo', 'Czechia', 'TEAM_LOGO'),
    ('CZE 2', 'Matej Kovar', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 3', 'Jindrich Stanek', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 4', 'Ladislav Krejci', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 5', 'Vladimir Coufal', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 6', 'Jaroslav Zeleny', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 7', 'Tomas Holes', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 8', 'David Zima', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 9', 'Michal Sadilek', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 10', 'Lukas Provod', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 11', 'Lukas Cerv', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 12', 'Tomas Soucek', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 13', 'Team Photo', 'Czechia', 'TEAM_PHOTO'),
    ('CZE 14', 'Pavel Sulc', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 15', 'Matej Vydra', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 16', 'Vasil Kusej', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 17', 'Tomas Chory', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 18', 'Vaclav Cerny', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 19', 'Adam Hlozek', 'Czechia', 'PLAYER_STICKER'),
    ('CZE 20', 'Patrik Schick', 'Czechia', 'PLAYER_STICKER'),
    ('ECU 1', 'Team Logo', 'Ecuador', 'TEAM_LOGO'),
    ('ECU 2', 'Hernán Galíndez', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 3', 'Gonzalo Valle', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 4', 'Piero Hincapié', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 5', 'Pervis Estupiñán', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 6', 'Willian Pacho', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 7', 'Ángelo Preciado', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 8', 'Joel Ordóñez', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 9', 'Moises Caicedo', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 10', 'Alan Franco', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 11', 'Kendry Paez', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 12', 'Pedro Vite', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 13', 'Team Photo', 'Ecuador', 'TEAM_PHOTO'),
    ('ECU 14', 'John Veboah', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 15', 'Leonardo Campana', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 16', 'Gonzalo Plata', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 17', 'Nilson Angulo', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 18', 'Alan Minda', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 19', 'Kevin Rodriguez', 'Ecuador', 'PLAYER_STICKER'),
    ('ECU 20', 'Enner Valencia', 'Ecuador', 'PLAYER_STICKER'),
    ('EGY 1', 'Team Logo', 'Egypt', 'TEAM_LOGO'),
    ('EGY 2', 'Mohamed El Shenawy', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 3', 'Mohamed Hany', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 4', 'Mohamed Hamdy', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 5', 'Yasser Ibrahim', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 6', 'Khaled Sobhi', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 7', 'Ramy Rabia', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 8', 'Hossam Abdelmaguid', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 9', 'Ahmed Fatouh', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 10', 'Marwan Attia', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 11', 'Zizo', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 12', 'Hamdy Fathy', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 13', 'Team Photo', 'Egypt', 'TEAM_PHOTO'),
    ('EGY 14', 'Mohamed Lasheen', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 15', 'Emam Ashour', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 16', 'Osama Faisal', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 17', 'Mohamed Salah', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 18', 'Mostafa Mohamed', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 19', 'Trezeguet', 'Egypt', 'PLAYER_STICKER'),
    ('EGY 20', 'Omar Marmoush', 'Egypt', 'PLAYER_STICKER'),
    ('ENG 1', 'Team Logo', 'England', 'TEAM_LOGO'),
    ('ENG 2', 'Jordan Pickford', 'England', 'PLAYER_STICKER'),
    ('ENG 3', 'John Stones', 'England', 'PLAYER_STICKER'),
    ('ENG 4', 'Marc Guéhi', 'England', 'PLAYER_STICKER'),
    ('ENG 5', 'Ezri Konsa', 'England', 'PLAYER_STICKER'),
    ('ENG 6', 'Trent Alexander-Arnold', 'England', 'PLAYER_STICKER'),
    ('ENG 7', 'Reece James', 'England', 'PLAYER_STICKER'),
    ('ENG 8', 'Dan Burn', 'England', 'PLAYER_STICKER'),
    ('ENG 9', 'Jordan Henderson', 'England', 'PLAYER_STICKER'),
    ('ENG 10', 'Declan Rice', 'England', 'PLAYER_STICKER'),
    ('ENG 11', 'Jude Bellingham', 'England', 'PLAYER_STICKER'),
    ('ENG 12', 'Cole Palmer', 'England', 'PLAYER_STICKER'),
    ('ENG 13', 'Team Photo', 'England', 'TEAM_PHOTO'),
    ('ENG 14', 'Morgan Rogers', 'England', 'PLAYER_STICKER'),
    ('ENG 15', 'Anthony Gordon', 'England', 'PLAYER_STICKER'),
    ('ENG 16', 'Phil Foden', 'England', 'PLAYER_STICKER'),
    ('ENG 17', 'Bukayo Saka', 'England', 'PLAYER_STICKER'),
    ('ENG 18', 'Harry Kane', 'England', 'PLAYER_STICKER'),
    ('ENG 19', 'Marcus Rashford', 'England', 'PLAYER_STICKER'),
    ('ENG 20', 'Ollie Watkins', 'England', 'PLAYER_STICKER'),
    ('ESP 1', 'Team Logo', 'Spain', 'TEAM_LOGO'),
    ('ESP 2', 'Unai Simon', 'Spain', 'PLAYER_STICKER'),
    ('ESP 3', 'Robin Le Normand', 'Spain', 'PLAYER_STICKER'),
    ('ESP 4', 'Aymeric Laporte', 'Spain', 'PLAYER_STICKER'),
    ('ESP 5', 'Dean Huijsen', 'Spain', 'PLAYER_STICKER'),
    ('ESP 6', 'Pedro Porro', 'Spain', 'PLAYER_STICKER'),
    ('ESP 7', 'Dani Carvajal', 'Spain', 'PLAYER_STICKER'),
    ('ESP 8', 'Marc Cucurella', 'Spain', 'PLAYER_STICKER'),
    ('ESP 9', 'Martín Zubimendi', 'Spain', 'PLAYER_STICKER'),
    ('ESP 10', 'Rodri', 'Spain', 'PLAYER_STICKER'),
    ('ESP 11', 'Pedri', 'Spain', 'PLAYER_STICKER'),
    ('ESP 12', 'Fabian Ruiz', 'Spain', 'PLAYER_STICKER'),
    ('ESP 13', 'Team Photo', 'Spain', 'TEAM_PHOTO'),
    ('ESP 14', 'Mikel Merino', 'Spain', 'PLAYER_STICKER'),
    ('ESP 15', 'Lamine Yamal', 'Spain', 'PLAYER_STICKER'),
    ('ESP 16', 'Dani Olmo', 'Spain', 'PLAYER_STICKER'),
    ('ESP 17', 'Nico Williams', 'Spain', 'PLAYER_STICKER'),
    ('ESP 18', 'Ferran Torres', 'Spain', 'PLAYER_STICKER'),
    ('ESP 19', 'Álvaro Morata', 'Spain', 'PLAYER_STICKER'),
    ('ESP 20', 'Mikel Oyarzabal', 'Spain', 'PLAYER_STICKER'),
    ('FRA 1', 'Team Logo', 'France', 'TEAM_LOGO'),
    ('FRA 2', 'Mike Maignan', 'France', 'PLAYER_STICKER'),
    ('FRA 3', 'Theo Hernandez', 'France', 'PLAYER_STICKER'),
    ('FRA 4', 'William Saliba', 'France', 'PLAYER_STICKER'),
    ('FRA 5', 'Jules Kounde', 'France', 'PLAYER_STICKER'),
    ('FRA 6', 'Ibrahima Konate', 'France', 'PLAYER_STICKER'),
    ('FRA 7', 'Dayot Upamecano', 'France', 'PLAYER_STICKER'),
    ('FRA 8', 'Lucas Digne', 'France', 'PLAYER_STICKER'),
    ('FRA 9', 'Aurélien Tchouaméni', 'France', 'PLAYER_STICKER'),
    ('FRA 10', 'Eduardo Camavinga', 'France', 'PLAYER_STICKER'),
    ('FRA 11', 'Manu Kone', 'France', 'PLAYER_STICKER'),
    ('FRA 12', 'Adrien Rabiot', 'France', 'PLAYER_STICKER'),
    ('FRA 13', 'Team Photo', 'France', 'TEAM_PHOTO'),
    ('FRA 14', 'Michael Olise', 'France', 'PLAYER_STICKER'),
    ('FRA 15', 'Ousmane Dembele', 'France', 'PLAYER_STICKER'),
    ('FRA 16', 'Bradley Barcola', 'France', 'PLAYER_STICKER'),
    ('FRA 17', 'Désiré Doué', 'France', 'PLAYER_STICKER'),
    ('FRA 18', 'Kingsley Coman', 'France', 'PLAYER_STICKER'),
    ('FRA 19', 'Hugo Ekitike', 'France', 'PLAYER_STICKER'),
    ('FRA 20', 'Kylian Mbappe', 'France', 'PLAYER_STICKER'),
    ('GER 1', 'Team Logo', 'Germany', 'TEAM_LOGO'),
    ('GER 2', 'Marc-André ter Stegen', 'Germany', 'PLAYER_STICKER'),
    ('GER 3', 'Jonathan Tah', 'Germany', 'PLAYER_STICKER'),
    ('GER 4', 'David Raum', 'Germany', 'PLAYER_STICKER'),
    ('GER 5', 'Nico Schlotterbeck', 'Germany', 'PLAYER_STICKER'),
    ('GER 6', 'Antonio Rüdiger', 'Germany', 'PLAYER_STICKER'),
    ('GER 7', 'Waldemar Anton', 'Germany', 'PLAYER_STICKER'),
    ('GER 8', 'Ridle Baku', 'Germany', 'PLAYER_STICKER'),
    ('GER 9', 'Maximilian Mittelstadt', 'Germany', 'PLAYER_STICKER'),
    ('GER 10', 'Joshua Kimmich', 'Germany', 'PLAYER_STICKER'),
    ('GER 11', 'Florian Wirtz', 'Germany', 'PLAYER_STICKER'),
    ('GER 12', 'Felix Nmecha', 'Germany', 'PLAYER_STICKER'),
    ('GER 13', 'Team Photo', 'Germany', 'TEAM_PHOTO'),
    ('GER 14', 'Leon Goretzka', 'Germany', 'PLAYER_STICKER'),
    ('GER 15', 'Jamal Musiala', 'Germany', 'PLAYER_STICKER'),
    ('GER 16', 'Serge Gnabry', 'Germany', 'PLAYER_STICKER'),
    ('GER 17', 'Kai Havertz', 'Germany', 'PLAYER_STICKER'),
    ('GER 18', 'Leroy Sane', 'Germany', 'PLAYER_STICKER'),
    ('GER 19', 'Karim Adeyemi', 'Germany', 'PLAYER_STICKER'),
    ('GER 20', 'Nick Woltemade', 'Germany', 'PLAYER_STICKER'),
    ('GHA 1', 'Team Logo', 'Ghana', 'TEAM_LOGO'),
    ('GHA 2', 'Lawrence Ati Zigi', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 3', 'Tariq Lamptey', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 4', 'Mohammed Salisu', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 5', 'Alidu Seidu', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 6', 'Alexander Djiku', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 7', 'Gideon Mensah', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 8', 'Caleb Yirenkyi', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 9', 'Abdul Issahaku Fatawu', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 10', 'Thomas Partey', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 11', 'Salis Abdul Samed', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 12', 'Kamaldeen Sulemana', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 13', 'Team Photo', 'Ghana', 'TEAM_PHOTO'),
    ('GHA 14', 'Mohammed Kudus', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 15', 'Inaki Williams', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 16', 'Jordan Ayew', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 17', 'Andrew Ayew', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 18', 'Joseph Paintsil', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 19', 'Osman Bukari', 'Ghana', 'PLAYER_STICKER'),
    ('GHA 20', 'Antoine Semenyo', 'Ghana', 'PLAYER_STICKER'),
    ('HAI 1', 'Team Logo', 'Haiti', 'TEAM_LOGO'),
    ('HAI 2', 'Johny Placide', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 3', 'Carlens Arcus', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 4', 'Martin Expérience', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 5', 'Jean-Kevin Duverne', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 6', 'Ricardo Adé', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 7', 'Duke Lacroix', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 8', 'Garven Metusala', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 9', 'Hannes Delcroix', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 10', 'Leverton Pierre', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 11', 'Danley Jean Jacques', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 12', 'Jean-Ricner Bellegarde', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 13', 'Team Photo', 'Haiti', 'TEAM_PHOTO'),
    ('HAI 14', 'Christopher Attys', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 15', 'Derrick Etienne Jr', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 16', 'Josue Casimir', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 17', 'Ruben Providence', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 18', 'Duckens Nazon', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 19', 'Louicius Deedson', 'Haiti', 'PLAYER_STICKER'),
    ('HAI 20', 'Frantzdy Pierrot', 'Haiti', 'PLAYER_STICKER'),
    ('IRN 1', 'Team Logo', 'Iran', 'TEAM_LOGO'),
    ('IRN 2', 'Alireza Beiranvand', 'Iran', 'PLAYER_STICKER'),
    ('IRN 3', 'Morteza Pouraliganji', 'Iran', 'PLAYER_STICKER'),
    ('IRN 4', 'Ehsan Hajsafi', 'Iran', 'PLAYER_STICKER'),
    ('IRN 5', 'Milad Mohammadi', 'Iran', 'PLAYER_STICKER'),
    ('IRN 6', 'Shojae Khalilzadeh', 'Iran', 'PLAYER_STICKER'),
    ('IRN 7', 'Ramin Rezaeian', 'Iran', 'PLAYER_STICKER'),
    ('IRN 8', 'Hossein Kanaani', 'Iran', 'PLAYER_STICKER'),
    ('IRN 9', 'Sadegh Moharrami', 'Iran', 'PLAYER_STICKER'),
    ('IRN 10', 'Saleh Hardani', 'Iran', 'PLAYER_STICKER'),
    ('IRN 11', 'Saeed Ezatolahi', 'Iran', 'PLAYER_STICKER'),
    ('IRN 12', 'Saman Ghoddos', 'Iran', 'PLAYER_STICKER'),
    ('IRN 13', 'Team Photo', 'Iran', 'TEAM_PHOTO'),
    ('IRN 14', 'Omid Noorafkan', 'Iran', 'PLAYER_STICKER'),
    ('IRN 15', 'Roozbeh Cheshmi', 'Iran', 'PLAYER_STICKER'),
    ('IRN 16', 'Mohammad Mohebi', 'Iran', 'PLAYER_STICKER'),
    ('IRN 17', 'Sardar Azmoun', 'Iran', 'PLAYER_STICKER'),
    ('IRN 18', 'Mehdi Taremi', 'Iran', 'PLAYER_STICKER'),
    ('IRN 19', 'Alireza Jahanbakhsh', 'Iran', 'PLAYER_STICKER'),
    ('IRN 20', 'Ali Gholizadeh', 'Iran', 'PLAYER_STICKER'),
    ('IRQ 1', 'Team Logo', 'Iraq', 'TEAM_LOGO'),
    ('IRQ 2', 'Jalal Hassan', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 3', 'Rebin Sulaka', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 4', 'Hussein Ali', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 5', 'Akam Hashem', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 6', 'Merchas Doski', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 7', 'Zaid Tahseen', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 8', 'Manaf Younis', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 9', 'Zidane Iqbal', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 10', 'Amir Al-Ammari', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 11', 'Ibrahim Bavesh', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 12', 'Ali Jasim', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 13', 'Team Photo', 'Iraq', 'TEAM_PHOTO'),
    ('IRQ 14', 'Youssef Amyn', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 15', 'Aimar Sher', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 16', 'Marko Farji', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 17', 'Osama Rashid', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 18', 'Ali Al-Hamadi', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 19', 'Aymen Hussein', 'Iraq', 'PLAYER_STICKER'),
    ('IRQ 20', 'Mohanad Ali', 'Iraq', 'PLAYER_STICKER'),
    ('JOR 1', 'Team Logo', 'Jordan', 'TEAM_LOGO'),
    ('JOR 2', 'Yazeed Abulaila', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 3', 'Ihsan Haddad', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 4', 'Mohammad Abu Hashish', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 5', 'Yazan Al-Arab', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 6', 'Abdallah Nasib', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 7', 'Saleem Obaid', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 8', 'Mohammad Abualnadi', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 9', 'Ibrahim Saadeh', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 10', 'Nizar Al-Rashdan', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 11', 'Noor Al-Rawabdeh', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 12', 'Mohannad Abu Taha', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 13', 'Team Photo', 'Jordan', 'TEAM_PHOTO'),
    ('JOR 14', 'Amer Jamous', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 15', 'Musa Al-Taamari', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 16', 'Yazan Al-Naimat', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 17', 'Mahmoud Al-Mardi', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 18', 'Ali Olwan', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 19', 'Mohammad Abu Zrayq', 'Jordan', 'PLAYER_STICKER'),
    ('JOR 20', 'Ibrahim Sabra', 'Jordan', 'PLAYER_STICKER'),
    ('JPN 1', 'Team Logo', 'Japan', 'TEAM_LOGO'),
    ('JPN 2', 'Zion Suzuki', 'Japan', 'PLAYER_STICKER'),
    ('JPN 3', 'Henry Heroki Mochizuki', 'Japan', 'PLAYER_STICKER'),
    ('JPN 4', 'Ayumu Seko', 'Japan', 'PLAYER_STICKER'),
    ('JPN 5', 'Junnosuke Suzuki', 'Japan', 'PLAYER_STICKER'),
    ('JPN 6', 'Shogo Taniguchi', 'Japan', 'PLAYER_STICKER'),
    ('JPN 7', 'Tsuyoshi Watanabe', 'Japan', 'PLAYER_STICKER'),
    ('JPN 8', 'Kaishu Sano', 'Japan', 'PLAYER_STICKER'),
    ('JPN 9', 'Yuki Soma', 'Japan', 'PLAYER_STICKER'),
    ('JPN 10', 'Ao Tanaka', 'Japan', 'PLAYER_STICKER'),
    ('JPN 11', 'Daichi Kamada', 'Japan', 'PLAYER_STICKER'),
    ('JPN 12', 'Takefusa Kubo', 'Japan', 'PLAYER_STICKER'),
    ('JPN 13', 'Team Photo', 'Japan', 'TEAM_PHOTO'),
    ('JPN 14', 'Ritsu Doan', 'Japan', 'PLAYER_STICKER'),
    ('JPN 15', 'Keito Nakamura', 'Japan', 'PLAYER_STICKER'),
    ('JPN 16', 'Takumi Minamino', 'Japan', 'PLAYER_STICKER'),
    ('JPN 17', 'Shuto Machino', 'Japan', 'PLAYER_STICKER'),
    ('JPN 18', 'Junya Ito', 'Japan', 'PLAYER_STICKER'),
    ('JPN 19', 'Koki Ogawa', 'Japan', 'PLAYER_STICKER'),
    ('JPN 20', 'Ayase Ueda', 'Japan', 'PLAYER_STICKER'),
    ('KOR 1', 'Team Logo', 'South Korea', 'TEAM_LOGO'),
    ('KOR 2', 'Hyeon-woo Jo', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 3', 'Seung-Gyu Kim', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 4', 'Min-jae Kim', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 5', 'Yu-min Cho', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 6', 'Young-woo Seol', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 7', 'Han-beom Lee', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 8', 'Tae-seok Lee', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 9', 'Myung-jae Lee', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 10', 'Jae-sung Lee', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 11', 'In-beom Hwang', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 12', 'Kang-in Lee', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 13', 'Team Photo', 'South Korea', 'TEAM_PHOTO'),
    ('KOR 14', 'Seung-ho Paik', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 15', 'Jens Castrop', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 16', 'Dongg-yeong Lee', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 17', 'Gue-sung Cho', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 18', 'Heung-min Son', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 19', 'Hee-chan Hwang', 'South Korea', 'PLAYER_STICKER'),
    ('KOR 20', 'Hyeon-Gyu Oh', 'South Korea', 'PLAYER_STICKER'),
    ('KSA 1', 'Team Logo', 'Saudi Arabia', 'TEAM_LOGO'),
    ('KSA 2', 'Nawaf Alaqidi', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 3', 'Abdulrahman Al-Sanbi', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 4', 'Saud Abdulhamid', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 5', 'Nawaf Bouwashl', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 6', 'Jihad Thakri', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 7', 'Moteb Al-Harbi', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 8', 'Hassan Altambakti', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 9', 'Musab Aljuwayr', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 10', 'Ziyad Aljohani', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 11', 'Abdullah Alkhaibari', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 12', 'Nasser Aldawsari', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 13', 'Team Photo', 'Saudi Arabia', 'TEAM_PHOTO'),
    ('KSA 14', 'Saleh Abu Alshamat', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 15', 'Marwan Alsahafi', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 16', 'Salem Aldawsari', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 17', 'Abdulrahman Al-Aboud', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 18', 'Feras Akbrikan', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 19', 'Saleh Alshehri', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('KSA 20', 'Abdullah Al-Hamdan', 'Saudi Arabia', 'PLAYER_STICKER'),
    ('MAR 1', 'Team Logo', 'Morocco', 'TEAM_LOGO'),
    ('MAR 2', 'Yassine Bounou', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 3', 'Munir El Kajoui', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 4', 'Achraf Hakimi', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 5', 'Noussair Mazraoui', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 6', 'Nayef Aguerd', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 7', 'Roman Saiss', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 8', 'Jawad El Yamio', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 9', 'Adam Masina', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 10', 'Sofyan Amrabat', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 11', 'Azzedine Ounahi', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 12', 'Eliesse Ben Seghir', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 13', 'Team Photo', 'Morocco', 'TEAM_PHOTO'),
    ('MAR 14', 'Bilal El Khannouss', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 15', 'Ismael Saibari', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 16', 'Youssef En-Nesyri', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 17', 'Abde Ezzalzouli', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 18', 'Soufiane Rahimi', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 19', 'Brahim Diaz', 'Morocco', 'PLAYER_STICKER'),
    ('MAR 20', 'Ayoub El Kaabi', 'Morocco', 'PLAYER_STICKER'),
    ('MEX 1', 'Team Logo', 'Mexico', 'TEAM_LOGO'),
    ('MEX 2', 'Luis Malagón', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 3', 'Johan Vasquez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 4', 'Jorge Sánchez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 5', 'Cesar Montes', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 6', 'Jesus Gallardo', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 7', 'Israel Reyes', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 8', 'Diego Lainez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 9', 'Carlos Rodriguez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 10', 'Edson Alvarez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 11', 'Orbelin Pineda', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 12', 'Marcel Ruiz', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 13', 'Team Photo', 'Mexico', 'TEAM_PHOTO'),
    ('MEX 14', 'Érick Sánchez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 15', 'Hirving Lozano', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 16', 'Santiago Giménez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 17', 'Raúl Jiménez', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 18', 'Alexis Vega', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 19', 'Roberto Alvarado', 'Mexico', 'PLAYER_STICKER'),
    ('MEX 20', 'Cesar Huerta', 'Mexico', 'PLAYER_STICKER'),
    ('NED 1', 'Team Logo', 'Netherlands', 'TEAM_LOGO'),
    ('NED 2', 'Bart Verbruggen', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 3', 'Virgil van Dijk', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 4', 'Micky van de Ven', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 5', 'Jurrien Timber', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 6', 'Denzel Dumfries', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 7', 'Nathan Aké', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 8', 'Jeremie Frimpong', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 9', 'Jan Paul van Hecke', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 10', 'Tijjani Reijnders', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 11', 'Ryan Gravenberch', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 12', 'Teun Koopmeiners', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 13', 'Team Photo', 'Netherlands', 'TEAM_PHOTO'),
    ('NED 14', 'Frenkie de Jong', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 15', 'Xavi Simons', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 16', 'Justin Kluivert', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 17', 'Memphis Depay', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 18', 'Donyell Malen', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 19', 'Wout Weghorst', 'Netherlands', 'PLAYER_STICKER'),
    ('NED 20', 'Cody Gakpo', 'Netherlands', 'PLAYER_STICKER'),
    ('NOR 1', 'Team Logo', 'Norway', 'TEAM_LOGO'),
    ('NOR 2', 'Orjan Nyland', 'Norway', 'PLAYER_STICKER'),
    ('NOR 3', 'Julian Ryerson', 'Norway', 'PLAYER_STICKER'),
    ('NOR 4', 'Leo Ostigård', 'Norway', 'PLAYER_STICKER'),
    ('NOR 5', 'Kristoffer Vassbakk Ajer', 'Norway', 'PLAYER_STICKER'),
    ('NOR 6', 'Marcus Holmgren Pedersen', 'Norway', 'PLAYER_STICKER'),
    ('NOR 7', 'David Møller Wolfe', 'Norway', 'PLAYER_STICKER'),
    ('NOR 8', 'Torbjørn Heggem', 'Norway', 'PLAYER_STICKER'),
    ('NOR 9', 'Morten Thorsby', 'Norway', 'PLAYER_STICKER'),
    ('NOR 10', 'Martin Ødegaard', 'Norway', 'PLAYER_STICKER'),
    ('NOR 11', 'Sander Berge', 'Norway', 'PLAYER_STICKER'),
    ('NOR 12', 'Andreas Schjelderup', 'Norway', 'PLAYER_STICKER'),
    ('NOR 13', 'Team Photo', 'Norway', 'TEAM_PHOTO'),
    ('NOR 14', 'Patrick Berg', 'Norway', 'PLAYER_STICKER'),
    ('NOR 15', 'Erling Haaland', 'Norway', 'PLAYER_STICKER'),
    ('NOR 16', 'Alexander Sørloth', 'Norway', 'PLAYER_STICKER'),
    ('NOR 17', 'Aron Dønnum', 'Norway', 'PLAYER_STICKER'),
    ('NOR 18', 'Jorgen Strand Larsen', 'Norway', 'PLAYER_STICKER'),
    ('NOR 19', 'Antonio Nusa', 'Norway', 'PLAYER_STICKER'),
    ('NOR 20', 'Oscar Bobb', 'Norway', 'PLAYER_STICKER'),
    ('NZL 1', 'Team Logo', 'New Zealand', 'TEAM_LOGO'),
    ('NZL 2', 'Max Crocombe Payne', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 3', 'Alex Paulsen', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 4', 'Michael Boxall', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 5', 'Liberato Cacace', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 6', 'Tim Payne', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 7', 'Tyler Bindon', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 8', 'Francis de Vries', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 9', 'Finn Surman', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 10', 'Joe Bell', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 11', 'Sarpreet Singh', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 12', 'Ryan Thomas', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 13', 'Team Photo', 'New Zealand', 'TEAM_PHOTO'),
    ('NZL 14', 'Matthew Garbett', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 15', 'Marko Stamenić', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 16', 'Ben Old', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 17', 'Chris Wood', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 18', 'Elijah Just', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 19', 'Callum McCowatt', 'New Zealand', 'PLAYER_STICKER'),
    ('NZL 20', 'Kosta Barbarouses', 'New Zealand', 'PLAYER_STICKER'),
    ('PAN 1', 'Team Logo', 'Panama', 'TEAM_LOGO'),
    ('PAN 2', 'Orlando Mosquera', 'Panama', 'PLAYER_STICKER'),
    ('PAN 3', 'Luis Mejia', 'Panama', 'PLAYER_STICKER'),
    ('PAN 4', 'Fidel Escobar', 'Panama', 'PLAYER_STICKER'),
    ('PAN 5', 'Andres Andrade', 'Panama', 'PLAYER_STICKER'),
    ('PAN 6', 'Michael Amir Murillo', 'Panama', 'PLAYER_STICKER'),
    ('PAN 7', 'Eric Davis', 'Panama', 'PLAYER_STICKER'),
    ('PAN 8', 'Jose Cordoba', 'Panama', 'PLAYER_STICKER'),
    ('PAN 9', 'Cesar Blackman', 'Panama', 'PLAYER_STICKER'),
    ('PAN 10', 'Cristian Martinez', 'Panama', 'PLAYER_STICKER'),
    ('PAN 11', 'Aníbal Godoy', 'Panama', 'PLAYER_STICKER'),
    ('PAN 12', 'Adalberto Carrasquilla', 'Panama', 'PLAYER_STICKER'),
    ('PAN 13', 'Team Photo', 'Panama', 'TEAM_PHOTO'),
    ('PAN 14', 'Édgar Bárcenas', 'Panama', 'PLAYER_STICKER'),
    ('PAN 15', 'Carlos Harvey', 'Panama', 'PLAYER_STICKER'),
    ('PAN 16', 'Ismael Díaz', 'Panama', 'PLAYER_STICKER'),
    ('PAN 17', 'Jose Fajardo', 'Panama', 'PLAYER_STICKER'),
    ('PAN 18', 'Cecilio Waterman', 'Panama', 'PLAYER_STICKER'),
    ('PAN 19', 'Jose Luiz Rodriguez', 'Panama', 'PLAYER_STICKER'),
    ('PAN 20', 'Alberto Quintero', 'Panama', 'PLAYER_STICKER'),
    ('PAR 1', 'Team Logo', 'Paraguay', 'TEAM_LOGO'),
    ('PAR 2', 'Roberto Fernandez', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 3', 'Orlando Gill', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 4', 'Gustavo Gomez', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 5', 'Fabián Balbuena', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 6', 'Juan José Cáceres', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 7', 'Omar Alderete', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 8', 'Junior Alonso', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 9', 'Mathías Villasanti', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 10', 'Diego Gomez', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 11', 'Damián Bobadilla', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 12', 'Andres Cubas', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 13', 'Team Photo', 'Paraguay', 'TEAM_PHOTO'),
    ('PAR 14', 'Matias Galarza Fonda', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 15', 'Julio Enciso', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 16', 'Alejandro Romero Gamarra', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 17', 'Miguel Almirón', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 18', 'Ramon Sosa', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 19', 'Angel Romero', 'Paraguay', 'PLAYER_STICKER'),
    ('PAR 20', 'Antonio Sanabria', 'Paraguay', 'PLAYER_STICKER'),
    ('POR 1', 'Team Logo', 'Portugal', 'TEAM_LOGO'),
    ('POR 2', 'Diogo Costa', 'Portugal', 'PLAYER_STICKER'),
    ('POR 3', 'Jose Sa', 'Portugal', 'PLAYER_STICKER'),
    ('POR 4', 'Ruben Dias', 'Portugal', 'PLAYER_STICKER'),
    ('POR 5', 'João Cancelo', 'Portugal', 'PLAYER_STICKER'),
    ('POR 6', 'Diogo Dalot', 'Portugal', 'PLAYER_STICKER'),
    ('POR 7', 'Nuno Mendes', 'Portugal', 'PLAYER_STICKER'),
    ('POR 8', 'Gonçalo Inácio', 'Portugal', 'PLAYER_STICKER'),
    ('POR 9', 'Bernardo Silva', 'Portugal', 'PLAYER_STICKER'),
    ('POR 10', 'Bruno Fernandes', 'Portugal', 'PLAYER_STICKER'),
    ('POR 11', 'Ruben Neves', 'Portugal', 'PLAYER_STICKER'),
    ('POR 12', 'Vitinha', 'Portugal', 'PLAYER_STICKER'),
    ('POR 13', 'Team Photo', 'Portugal', 'TEAM_PHOTO'),
    ('POR 14', 'João Neves', 'Portugal', 'PLAYER_STICKER'),
    ('POR 15', 'Cristiano Ronaldo', 'Portugal', 'PLAYER_STICKER'),
    ('POR 16', 'Francisco Trincao', 'Portugal', 'PLAYER_STICKER'),
    ('POR 17', 'João Felix', 'Portugal', 'PLAYER_STICKER'),
    ('POR 18', 'Gonçalo Ramos', 'Portugal', 'PLAYER_STICKER'),
    ('POR 19', 'Pedro Neto', 'Portugal', 'PLAYER_STICKER'),
    ('POR 20', 'Rafael Leão', 'Portugal', 'PLAYER_STICKER'),
    ('QAT 1', 'Team Logo', 'Qatar', 'TEAM_LOGO'),
    ('QAT 2', 'Meshaal Barsham', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 3', 'Sultan Albrake', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 4', 'Lucas Mendes', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 5', 'Homam Ahmed', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 6', 'Boualem Khoukhi', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 7', 'Pedro Miguel', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 8', 'Tarek Salman', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 9', 'Mohamed Al-Mannai', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 10', 'Karim Boudiaf', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 11', 'Assim Madibo', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 12', 'Ahmed Fatehi', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 13', 'Team Photo', 'Qatar', 'TEAM_PHOTO'),
    ('QAT 14', 'Mohammed Waad', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 15', 'Abdulaziz Hatem', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 16', 'Hassan Al-Haydos', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 17', 'Edmilson Junior', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 18', 'Akram Hassan Afif', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 19', 'Ahmed Al Ganehi', 'Qatar', 'PLAYER_STICKER'),
    ('QAT 20', 'Almoez Ali', 'Qatar', 'PLAYER_STICKER'),
    ('RSA 1', 'Team Logo', 'South Africa', 'TEAM_LOGO'),
    ('RSA 2', 'Ronwen Williams', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 3', 'Sipho Chaine', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 4', 'Aubrey Modiba', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 5', 'Samukele Kabini', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 6', 'Mbekezeli Mbokazi', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 7', 'Khulumani Ndamane', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 8', 'Siyabonga Ngezana', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 9', 'Khuliso Mudau', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 10', 'Nkosinathi Sibisi', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 11', 'Teboho Mokoena', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 12', 'Thalente Mbatha', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 13', 'Team Photo', 'South Africa', 'TEAM_PHOTO'),
    ('RSA 14', 'Bathasi Aubaas', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 15', 'Yaya Sithole', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 16', 'Sipho Mbule', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 17', 'Lyle Foster', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 18', 'Iqraam Rayners', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 19', 'Mohau Nkota', 'South Africa', 'PLAYER_STICKER'),
    ('RSA 20', 'Oswin Appollis', 'South Africa', 'PLAYER_STICKER'),
    ('SCO 1', 'Team Logo', 'Scotland', 'TEAM_LOGO'),
    ('SCO 2', 'Angus Gunn', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 3', 'Jack Hendry', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 4', 'Kieran Tierney', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 5', 'Aaron Hickey', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 6', 'Andrew Robertson', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 7', 'Scott McKenna', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 8', 'John Souttar', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 9', 'Anthony Ralston', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 10', 'Grant Hanley', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 11', 'Scott McTominay', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 12', 'Billy Gilmour', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 13', 'Team Photo', 'Scotland', 'TEAM_PHOTO'),
    ('SCO 14', 'Lewis Ferguson', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 15', 'Ryan Christie', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 16', 'Kenny McLean', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 17', 'John McGinn', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 18', 'Lyndon Dykes', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 19', 'Che Adams', 'Scotland', 'PLAYER_STICKER'),
    ('SCO 20', 'Ben Gannon-Doak', 'Scotland', 'PLAYER_STICKER'),
    ('SEN 1', 'Team Logo', 'Senegal', 'TEAM_LOGO'),
    ('SEN 2', 'Edouard Mendy', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 3', 'Yehvann Diouf', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 4', 'Moussa Niakhaté', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 5', 'Abdoulaye Seck', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 6', 'Ismail Jakobs', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 7', 'El Hadji Malick Diouf', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 8', 'Kalidou Koulibaly', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 9', 'Idrissa Gana Gueye', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 10', 'Pape Matar Sarr', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 11', 'Pape Gueye', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 12', 'Habib Diarra', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 13', 'Team Photo', 'Senegal', 'TEAM_PHOTO'),
    ('SEN 14', 'Lamine Camara', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 15', 'Sadio Mane', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 16', 'Ismaïla Sarr', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 17', 'Boulaye Dia', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 18', 'Iliman Ndiaye', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 19', 'Nicolas Jackson', 'Senegal', 'PLAYER_STICKER'),
    ('SEN 20', 'Krepin Diatta', 'Senegal', 'PLAYER_STICKER'),
    ('SUI 1', 'Team Logo', 'Switzerland', 'TEAM_LOGO'),
    ('SUI 2', 'Gregor Kobel', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 3', 'Yvon Mvogo', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 4', 'Manuel Akanji', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 5', 'Ricardo Rodriguez', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 6', 'Nico Elvedi', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 7', 'Aurèle Amenda', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 8', 'Silvan Widmer', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 9', 'Granit Xhaka', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 10', 'Denis Zakaria', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 11', 'Remo Freuler', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 12', 'Fabian Rieder', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 13', 'Team Photo', 'Switzerland', 'TEAM_PHOTO'),
    ('SUI 14', 'Ardon Jashari', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 15', 'Johan Manzambi', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 16', 'Michel Aebischer', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 17', 'Breel Embolo', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 18', 'Ruben Vargas', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 19', 'Dan Ndoye', 'Switzerland', 'PLAYER_STICKER'),
    ('SUI 20', 'Zeki Amdouni', 'Switzerland', 'PLAYER_STICKER'),
    ('SWE 1', 'Team Logo', 'Sweden', 'TEAM_LOGO'),
    ('SWE 2', 'Victor Johansson', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 3', 'Isak Hien', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 4', 'Gabriel Gudmundsson', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 5', 'Emil Holm', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 6', 'Victor Nilsson Lindelöf', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 7', 'Gustaf Lagerbielke', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 8', 'Lucas Bergvall', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 9', 'Hugo Larsson', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 10', 'Jesper Karlström', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 11', 'Yasin Ayari', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 12', 'Mattias Svanberg', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 13', 'Team Photo', 'Sweden', 'TEAM_PHOTO'),
    ('SWE 14', 'Daniel Svensson', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 15', 'Ken Sema', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 16', 'Roony Bardghji', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 17', 'Dejan Kulusevski', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 18', 'Anthony Elanga', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 19', 'Alexander Isak', 'Sweden', 'PLAYER_STICKER'),
    ('SWE 20', 'Viktor Gyökeres', 'Sweden', 'PLAYER_STICKER'),
    ('TUN 1', 'Team Logo', 'Tunisia', 'TEAM_LOGO'),
    ('TUN 2', 'Bechir Ben Said', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 3', 'Aymen Dahmen', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 4', 'Yan Valery', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 5', 'Montassar Talbi', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 6', 'Yassine Meriah', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 7', 'Ali Abdi', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 8', 'Dylan Bronn', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 9', 'Ellyes Skhiri', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 10', 'Aissa Laidouni', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 11', 'Ferjani Sassi', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 12', 'Mohamed Ali Ben Romdhane', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 13', 'Team Photo', 'Tunisia', 'TEAM_PHOTO'),
    ('TUN 14', 'Hannibal Mejbri', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 15', 'Elias Achouri', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 16', 'Elias Saad', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 17', 'Hazem Mastouri', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 18', 'Ismael Gharbi', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 19', 'Sayfallah Ltaief', 'Tunisia', 'PLAYER_STICKER'),
    ('TUN 20', 'Naim Sliti', 'Tunisia', 'PLAYER_STICKER'),
    ('TUR 1', 'Team Logo', 'Turkey', 'TEAM_LOGO'),
    ('TUR 2', 'Ugurcan Cakir', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 3', 'Mert Muldur', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 4', 'Zeki Celik', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 5', 'Abdulkerim Bardakci', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 6', 'Caglar Soyuncu', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 7', 'Merih Demiral', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 8', 'Ferdi Kadioglu', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 9', 'Kaan Ayhan', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 10', 'Ismail Yuksek', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 11', 'Hakan Calhanoglu', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 12', 'Orkun Kokcu', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 13', 'Team Photo', 'Turkey', 'TEAM_PHOTO'),
    ('TUR 14', 'Arda Guler', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 15', 'Irfan Can Kahveci', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 16', 'Yunus Akgun', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 17', 'Can Uzun', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 18', 'Baris Alper Yilmaz', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 19', 'Kerem Akturkoglu', 'Turkey', 'PLAYER_STICKER'),
    ('TUR 20', 'Kenan Yildiz', 'Turkey', 'PLAYER_STICKER'),
    ('URU 1', 'Team Logo', 'Uruguay', 'TEAM_LOGO'),
    ('URU 2', 'Sergio Rochet', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 3', 'Santiago Mele', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 4', 'Ronald Araujo', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 5', 'José María Giménez', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 6', 'Sebastian Caceres', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 7', 'Mathias Olivera', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 8', 'Guillermo Varela', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 9', 'Nahitan Nandez', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 10', 'Federico Valverde', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 11', 'Giorgian De Arrascaeta', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 12', 'Rodrigo Bentancur', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 13', 'Team Photo', 'Uruguay', 'TEAM_PHOTO'),
    ('URU 14', 'Manuel Ugarte', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 15', 'Nicolás de la Cruz', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 16', 'Maxi Araujo', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 17', 'Darwin Núñez', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 18', 'Federico Viñas', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 19', 'Rodrigo Aguirre', 'Uruguay', 'PLAYER_STICKER'),
    ('URU 20', 'Facundo Pellistri', 'Uruguay', 'PLAYER_STICKER'),
    ('USA 1', 'Team Logo', 'United States', 'TEAM_LOGO'),
    ('USA 2', 'Math Freese', 'United States', 'PLAYER_STICKER'),
    ('USA 3', 'Chris Richards', 'United States', 'PLAYER_STICKER'),
    ('USA 4', 'Tim Ream', 'United States', 'PLAYER_STICKER'),
    ('USA 5', 'Mark McKenzie', 'United States', 'PLAYER_STICKER'),
    ('USA 6', 'Alex Freeman', 'United States', 'PLAYER_STICKER'),
    ('USA 7', 'Antonee Robinson', 'United States', 'PLAYER_STICKER'),
    ('USA 8', 'Tyler Adams', 'United States', 'PLAYER_STICKER'),
    ('USA 9', 'Tanner Tessmann', 'United States', 'PLAYER_STICKER'),
    ('USA 10', 'Weston McKenny', 'United States', 'PLAYER_STICKER'),
    ('USA 11', 'Christian Roldan', 'United States', 'PLAYER_STICKER'),
    ('USA 12', 'Timothy Weah', 'United States', 'PLAYER_STICKER'),
    ('USA 13', 'Team Photo', 'United States', 'TEAM_PHOTO'),
    ('USA 14', 'Diego Luna', 'United States', 'PLAYER_STICKER'),
    ('USA 15', 'Malik Tillman', 'United States', 'PLAYER_STICKER'),
    ('USA 16', 'Christian Pulisic', 'United States', 'PLAYER_STICKER'),
    ('USA 17', 'Brenden Aaronson', 'United States', 'PLAYER_STICKER'),
    ('USA 18', 'Ricardo Pepi', 'United States', 'PLAYER_STICKER'),
    ('USA 19', 'Haji Wright', 'United States', 'PLAYER_STICKER'),
    ('USA 20', 'Folarin Balogun', 'United States', 'PLAYER_STICKER'),
    ('UZB 1', 'Team Logo', 'Uzbekistan', 'TEAM_LOGO'),
    ('UZB 2', 'Utkir Yusupov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 3', 'Farrukh Savfiev', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 4', 'Sherzod Nasrullaev', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 5', 'Umar Eshmurodov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 6', 'Husniddin Aliqulov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 7', 'Rustamjon Ashurmatov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 8', 'Khojiakbar Alijonov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 9', 'Abdukodir Khusanov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 10', 'Odiljon Hamrobekov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 11', 'Otabek Shukurov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 12', 'Jamshid Iskanderov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 13', 'Team Photo', 'Uzbekistan', 'TEAM_PHOTO'),
    ('UZB 14', 'Azizbek Turgunboev', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 15', 'Khojimat Erkinov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 16', 'Eldor Shomurodov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 17', 'Oston Urunov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 18', 'Jaloliddin Masharipov', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 19', 'Igor Sergeev', 'Uzbekistan', 'PLAYER_STICKER'),
    ('UZB 20', 'Abbosbek Fayzullaev', 'Uzbekistan', 'PLAYER_STICKER')
    ON CONFLICT (sticker_code) DO NOTHING;